@(
    @('b', 'false'),
    @('b', 'true'),
    @('d', '0.0'),
    @('d', '0.01'),
    @('d', '0.050000000000000003'),
    @('d', '0.10000000000000001'),
    @('g', 'signature ''ii'''),
    @('h', 'handle 0'),
    @('i', '-1'),
    @('i', '-2147483648'),
    @('i', '0'),
    @('i', '1'),
    @('n', 'int16 -32768'),
    @('o', 'objectpath ''/ca/desrt/dconf_editor'''),
    @('q', 'uint16 0'),
    @('q', 'uint16 3389'),
    @('q', 'uint16 5900'),
    @('q', 'uint16 65535'),
    @('s', '''_'''),
    @('s', '''-x'''),
    @('s', ''',.、。，．'''),
    @('s', ''''''),
    @('t', 'uint64 1735653874'),
    @('t', 'uint64 18446744073709551615'),
    @('t', 'uint64 50'),
    @('u', 'uint32 0'),
    @('u', 'uint32 100'),
    @('u', 'uint32 1800'),
    @('u', 'uint32 200'),
    @('v', '<(''template'', '''', '''', '''', false, 300, false, true, false, ''utf-8'')>'),
    @('v', '<@mmb just nothing>'),
    @('x', 'int64 -9223372036854775808'),
    @('x', 'int64 0'),
    @('x', 'int64 1730457901558100'),
    @('x', 'int64 1730488169'),
    @('y', 'byte 0x42'),
    @('()', '()'),
    @('ad', '[0.0, 0.0]'),
    @('ai', '[0]'),
    @('ai', '[2530, 1388]'),
    @('ai', '[26, 23]'),
    @('ai', '@ai []'),
    @('ao', '[objectpath ''/ca/desrt/dconf_editor/menus/appmenu'', ''/ca/desrt/dconf_editor/window/1'']'),
    @('as', '[''.trackerignore'', ''.git'', ''.hg'', ''.nomedia'']'),
    @('as', '['''', '''', ''Workspace 3'', ''Workspace 4'', ''Workspace 5'', ''Workspace 7'', ''Workspace 7'']'),
    @('as', '['''', ''<Super>F1'']'),
    @('as', '['''']'),
    @('av', '[<(''embedded'', ''般'', ''General'', '''', true, 0, true, true, false, ''utf-8'')>, <(''zipcode'', ''〒'', ''Zip Code Conversion'', '''', true, -1, false, true, false, ''utf-8'')>, <(''symbol'', ''記'', ''Symbol'', '''', true, -1, true, false, false, ''utf-8'')>, <(''oldchar'', ''旧'', ''Old Character Style'', '''', true, -1, false, true, false, ''utf-8'')>, <(''era'', ''年'', ''Era'', '''', true, -1, false, true, false, ''utf-8'')>, <(''emoji'', ''😊'', ''Emoji'', '''', true, -1, false, true, false, ''utf-8'')>]'),
    @('av', '@av []'),
    @('ay', '[byte 0x48, 0x65, 0x6c, 0x6c, 0x6c]'),
    @('mb', '@mb nothing'),
    @('ms', '@ms ''test'''),
    @('ms', '@ms nothing'),
    @('aas', '@aas []'),
    @('aay', '[[byte 0x48, 0x65, 0x6c, 0x6c, 0x6c], [0x57, 0x6f, 0x72, 0x6c, 0x64], [0x21]]'),
    @('(dd)', '(2.3523489932885906, 1.6247030878859858)'),
    @('(dd)', '(91.0, 181.0)'),
    @('(ii)', '(-1, -1)'),
    @('(ii)', '(1178, 1368)'),
    @('(ii)', '(1203, 902)'),
    @('(ii)', '(1341, 1368)'),
    @('{ss}', '{''color'', ''red''}'),
    @('(iib)', '(1358, 1368, false)'),
    @('a(ss)', '[(''xkb'', ''gb'')]'),
    @('a(ss)', '@a(ss) []'),
    @('a(us)', '[(uint32 0, ''#e01b24''), (1, ''#ff7800''), (2, ''#f6d32d''), (3, ''#33d17a''), (4, ''#26a269''), (5, ''#62a0ea''), (6, ''#1c71d8''), (7, ''#613583''), (8, ''#9141ac''), (9, ''#c061cb''), (10, ''#ffbe6f''), (11, ''#f9f06b''), (12, ''#8ff0a4''), (13, ''#2ec27e''), (14, ''#1a5fb4''), (15, ''#c061cb''), (16, ''#b01c7999f332''), (17, ''#7999f3328ca0''), (18, ''#f33279998a0c''), (19, ''#7999ad88f332''), (20, ''#d103f3327999''), (21, ''#f1e57999f332''), (22, ''#7999f332ce6a''), (23, ''#f332aaee7999'')]'),
    @('a{ss}', '{''ca.desrt.dconf-editor.Demo.Relocatable'': ''/ca/desrt/dconf-editor/Demo/relocatable/''}'),
    # @('a{sv}', '{''base'': <{''q'': <[''。'', '''', ''ぁ'']>, ''w'': <[''か'', ''が'', ''え'']>, ''e'': <[''た'', ''だ'', ''り'']>, ''r'': <[''こ'', ''ご'', ''ゃ'']>, ''t'': <[''さ'', ''ざ'', ''れ'']>, ''y'': <[''ら'', ''よ'', ''ぱ'']>, ''u'': <[''ち'', ''に'', ''ぢ'']>, ''i'': <[''く'', ''る'', ''ぐ'']>, ''o'': <[''つ'', ''ま'', ''づ'']>, ''p'': <[''，'', ''ぇ'', ''ぴ'']>, ''at'': <[''、'', '''', '''']>, ''bracketleft'': <[''゛'', ''゜'', '''']>, ''a'': <[''う'', '''', ''を'']>, ''s'': <[''し'', ''じ'', ''あ'']>, ''d'': <[''て'', ''で'', ''な'']>, ''f'': <[''け'', ''げ'', ''ゅ'']>, ''g'': <[''せ'', ''ぜ'', ''も'']>, ''h'': <[''は'', ''み'', ''ば'']>, ''j'': <[''と'', ''お'', ''ど'']>, ''k'': <[''き'', ''の'', ''ぎ'']>, ''l'': <[''い'', ''ょ'', ''ぽ'']>, ''semicolon'': <[''ん'', ''っ'', '''']>, ''z'': <[''．'', '''', ''ぅ'']>, ''x'': <[''ひ'', ''び'', ''ー'']>, ''c'': <[''す'', ''ず'', ''ろ'']>, ''v'': <[''ふ'', ''ぶ'', ''や'']>, ''b'': <[''へ'', ''べ'', ''ぃ'']>, ''n'': <[''め'', ''ぬ'', ''ぷ'']>, ''m'': <[''そ'', ''ゆ'', ''ぞ'']>, ''comma'': <[''ね'', ''む'', ''ぺ'']>, ''period'': <[''ほ'', ''わ'', ''ぼ'']>, ''slash'': <[''・'', ''ぉ'', '''']>, ''1'': <[''1'', '''', ''？'']>, ''2'': <[''2'', '''', ''／'']>, ''4'': <[''4'', '''', ''「'']>, ''5'': <[''5'', '''', ''」'']>, ''6'': <[''6'', ''［'', '''']>, ''7'': <[''7'', ''］'', '''']>, ''8'': <[''8'', ''（'', '''']>, ''9'': <[''9'', ''）'', '''']>, ''backslash'': <[''￥'', '''', '''']>}>, ''nicola-j-table'': <{''colon'': <[''：'', '''', '''']>, ''at'': <[''、'', '''', '''']>, ''bracketleft'': <[''゛'', ''゜'', '''']>, ''bracketright'': <[''」'', '''', '''']>, ''8'': <[''8'', ''（'', '''']>, ''9'': <[''9'', ''）'', '''']>, ''0'': <[''0'', '''', '''']>}>, ''nicola-a-table'': <{''colon'': <[''：'', '''', '''']>, ''at'': <[''＠'', '''', '''']>, ''bracketleft'': <[''、'', '''', '''']>, ''bracketright'': <[''゛'', ''゜'', '''']>, ''8'': <[''8'', '''', '''']>, ''9'': <[''9'', ''（'', '''']>, ''0'': <[''0'', ''）'', '''']>}>, ''nicola-f-table'': <{''colon'': <[''、'', '''', '''']>, ''at'': <[''＠'', '''', '''']>, ''bracketleft'': <[''゛'', ''゜'', '''']>, ''bracketright'': <[''」'', '''', '''']>, ''8'': <[''8'', ''（'', '''']>, ''9'': <[''9'', ''）'', '''']>, ''0'': <[''0'', '''', '''']>}>, ''kb231-j-fmv-table'': <{''3'': <[''3'', '''', ''～'']>, ''0'': <[''0'', ''『'', '''']>, ''minus'': <[''-'', ''』'', '''']>, ''equal'': <[''='', '''', '''']>}>, ''kb231-a-fmv-table'': <{''3'': <[''3'', '''', ''～'']>, ''0'': <[''0'', ''）'', '''']>, ''minus'': <[''-'', ''『'', '''']>, ''equal'': <[''='', ''』'', '''']>}>, ''kb231-f-fmv-table'': <{''3'': <[''3'', '''', ''～'']>, ''0'': <[''0'', ''『'', '''']>, ''minus'': <[''-'', ''』'', '''']>, ''equal'': <[''='', '''', '''']>}>, ''kb611-j-fmv-table'': <{''grave'': <[''‘'', '''', '''']>, ''asciicircum'': <[''々'', ''£'', '''']>, ''colon'': <[''：'', '''', '''']>, ''at'': <[''、'', ''¢'', '''']>, ''bracketleft'': <[''゛'', ''゜'', '''']>, ''backslash'': <[''￥'', ''¦'', '''']>}>, ''kb611-a-fmv-table'': <{''grave'': <[''々'', '''', ''£'']>, ''colon'': <[''：'', '''', '''']>, ''at'': <[''＠'', '''', '''']>, ''bracketleft'': <[''、'', ''¢'', '''']>, ''backslash'': <[''￥'', ''¦'', '''']>}>, ''kb611-f-fmv-table'': <{''grave'': <[''‘'', '''', '''']>, ''asciicircum'': <[''々'', ''£'', '''']>, ''colon'': <[''、'', ''¢'', '''']>, ''at'': <[''＠'', '''', '''']>, ''bracketleft'': <[''゛'', ''゜'', '''']>, ''backslash'': <[''￥'', ''¦'', '''']>}>}'),
    @('a{sv}', '{''cancel'': <[''Escape'']>, ''change_line_direction_left_to_right'': <@as []>, ''change_line_direction_right_to_left'': <@as []>, ''change_line_direction_toggle'': <@as []>, ''commit'': <@as []>, ''commit_and_forward_key'': <@as []>, ''commit_candidate_1'': <@as []>, ''commit_candidate_1_plus_space'': <[''1'', ''KP_1'', ''F1'']>, ''commit_candidate_2'': <@as []>, ''commit_candidate_2_plus_space'': <[''2'', ''KP_2'', ''F2'']>, ''commit_candidate_3'': <@as []>, ''commit_candidate_3_plus_space'': <[''3'', ''KP_3'', ''F3'']>, ''commit_candidate_4'': <@as []>, ''commit_candidate_4_plus_space'': <[''4'', ''KP_4'', ''F4'']>, ''commit_candidate_5'': <@as []>, ''commit_candidate_5_plus_space'': <[''5'', ''KP_5'', ''F5'']>, ''commit_candidate_6'': <@as []>, ''commit_candidate_6_plus_space'': <[''6'', ''KP_6'', ''F6'']>, ''commit_candidate_7'': <@as []>, ''commit_candidate_7_plus_space'': <[''7'', ''KP_7'', ''F7'']>, ''commit_candidate_8'': <@as []>, ''commit_candidate_8_plus_space'': <[''8'', ''KP_8'', ''F8'']>, ''commit_candidate_9'': <@as []>, ''commit_candidate_9_plus_space'': <[''9'', ''KP_9'', ''F9'']>, ''enable_lookup'': <[''Tab'', ''ISO_Left_Tab'']>, ''lookup_related'': <[''Mod5+F12'']>, ''lookup_table_page_up'': <[''Page_Up'', ''KP_Page_Up'', ''KP_Prior'']>, ''lookup_table_page_down'': <[''Page_Down'', ''KP_Page_Down'', ''KP_Next'']>, ''next_case_mode'': <[''Shift_L'']>, ''next_dictionary'': <[''Mod1+Down'', ''Mod1+KP_Down'']>, ''next_input_method'': <[''Control+Down'', ''Control+KP_Down'']>, ''previous_case_mode'': <[''Shift_R'']>, ''previous_input_method'': <[''Control+Up'', ''Control+KP_Up'']>, ''previous_dictionary'': <[''Mod1+Up'', ''Mod1+KP_Up'']>, ''remove_candidate_1'': <[''Control+1'', ''Control+KP_1'', ''Control+F1'']>, ''remove_candidate_2'': <[''Control+2'', ''Control+KP_2'', ''Control+F2'']>, ''remove_candidate_3'': <[''Control+3'', ''Control+KP_3'', ''Control+F3'']>, ''remove_candidate_4'': <[''Control+4'', ''Control+KP_4'', ''Control+F4'']>, ''remove_candidate_5'': <[''Control+5'', ''Control+KP_5'', ''Control+F5'']>, ''remove_candidate_6'': <[''Control+6'', ''Control+KP_6'', ''Control+F6'']>, ''remove_candidate_7'': <[''Control+7'', ''Control+KP_7'', ''Control+F7'']>, ''remove_candidate_8'': <[''Control+8'', ''Control+KP_8'', ''Control+F8'']>, ''remove_candidate_9'': <[''Control+9'', ''Control+KP_9'', ''Control+F9'']>, ''select_next_candidate'': <[''Tab'', ''ISO_Left_Tab'', ''Down'', ''KP_Down'']>, ''select_previous_candidate'': <[''Shift+Tab'', ''Shift+ISO_Left_Tab'', ''Up'', ''KP_Up'']>, ''setup'': <[''Mod5+F10'']>, ''speech_recognition'': <@as []>, ''toggle_emoji_prediction'': <[''Mod5+F6'']>, ''toggle_off_the_record'': <[''Mod5+F9'']>, ''toggle_ascii_digits'': <@as []>, ''toggle_hide_input'': <[''Shift+Control+Escape'']>, ''toggle_input_mode_on_off'': <@as []>}'),
    @('a{sv}', '{''default'': <{''minus'': <''ー''>, ''a'': <''あ''>, ''i'': <''い''>, ''u'': <''う''>, ''e'': <''え''>, ''o'': <''お''>, ''x-a'': <''ぁ''>, ''x-i'': <''ぃ''>, ''x-u'': <''ぅ''>, ''x-e'': <''ぇ''>, ''x-o'': <''ぉ''>, ''l-a'': <''ぁ''>, ''l-i'': <''ぃ''>, ''l-u'': <''ぅ''>, ''l-e'': <''ぇ''>, ''l-o'': <''ぉ''>, ''w-h-a'': <''うぁ''>, ''w-h-i'': <''うぃ''>, ''w-h-e'': <''うぇ''>, ''w-h-o'': <''うぉ''>, ''w-y-a'': <''うゃ''>, ''w-y-u'': <''うゅ''>, ''w-y-o'': <''うょ''>, ''v-a'': <''ヴぁ''>, ''v-i'': <''ヴぃ''>, ''v-u'': <''ヴ''>, ''v-e'': <''ヴぇ''>, ''v-o'': <''ヴぉ''>, ''v-y-a'': <''ヴゃ''>, ''v-y-u'': <''ヴゅ''>, ''v-y-e'': <''ヴぃぇ''>, ''v-y-o'': <''ヴょ''>, ''k-a'': <''か''>, ''k-i'': <''き''>, ''k-u'': <''く''>, ''k-e'': <''け''>, ''k-o'': <''こ''>, ''l-k-a'': <''ヵ''>, ''l-k-e'': <''ヶ''>, ''x-k-a'': <''ヵ''>, ''x-k-e'': <''ヶ''>, ''g-a'': <''が''>, ''g-i'': <''ぎ''>, ''g-u'': <''ぐ''>, ''g-e'': <''げ''>, ''g-o'': <''ご''>, ''k-y-a'': <''きゃ''>, ''k-y-i'': <''きぃ''>, ''k-y-u'': <''きゅ''>, ''k-y-e'': <''きぇ''>, ''k-y-o'': <''きょ''>, ''k-w-a'': <''くぁ''>, ''k-w-i'': <''くぃ''>, ''k-w-u'': <''くぅ''>, ''k-w-e'': <''くぇ''>, ''k-w-o'': <''くぉ''>, ''g-y-a'': <''ぎゃ''>, ''g-y-i'': <''ぎぃ''>, ''g-y-u'': <''ぎゅ''>, ''g-y-e'': <''ぎぇ''>, ''g-y-o'': <''ぎょ''>, ''g-w-a'': <''ぐぁ''>, ''g-w-i'': <''ぐぃ''>, ''g-w-u'': <''ぐぅ''>, ''g-w-e'': <''ぐぇ''>, ''g-w-o'': <''ぐぉ''>, ''s-a'': <''さ''>, ''s-i'': <''し''>, ''s-u'': <''す''>, ''s-e'': <''せ''>, ''s-o'': <''そ''>, ''z-a'': <''ざ''>, ''z-i'': <''じ''>, ''z-u'': <''ず''>, ''z-e'': <''ぜ''>, ''z-o'': <''ぞ''>, ''s-y-a'': <''しゃ''>, ''s-y-i'': <''しぃ''>, ''s-y-u'': <''しゅ''>, ''s-y-e'': <''しぇ''>, ''s-y-o'': <''しょ''>, ''s-h-a'': <''しゃ''>, ''s-h-i'': <''し''>, ''s-h-u'': <''しゅ''>, ''s-h-e'': <''しぇ''>, ''s-h-o'': <''しょ''>, ''z-y-a'': <''じゃ''>, ''z-y-i'': <''じぃ''>, ''z-y-u'': <''じゅ''>, ''z-y-e'': <''じぇ''>, ''z-y-o'': <''じょ''>, ''j-a'': <''じゃ''>, ''j-y-a'': <''じゃ''>, ''j-i'': <''じ''>, ''j-y-i'': <''じぃ''>, ''j-u'': <''じゅ''>, ''j-y-u'': <''じゅ''>, ''j-e'': <''じぇ''>, ''j-y-e'': <''じぇ''>, ''j-o'': <''じょ''>, ''j-y-o'': <''じょ''>, ''s-w-i'': <''すぅぃ''>, ''s-w-e'': <''すぇ''>, ''z-w-e'': <''ずぇ''>, ''t-a'': <''た''>, ''t-i'': <''ち''>, ''t-u'': <''つ''>, ''t-s-u'': <''つ''>, ''t-e'': <''て''>, ''t-o'': <''と''>, ''d-a'': <''だ''>, ''d-i'': <''ぢ''>, ''d-u'': <''づ''>, ''d-e'': <''で''>, ''d-o'': <''ど''>, ''x-t-u'': <''っ''>, ''x-t-s-u'': <''っ''>, ''l-t-u'': <''っ''>, ''l-t-s-u'': <''っ''>, ''t-y-a'': <''ちゃ''>, ''t-y-i'': <''ちぃ''>, ''t-y-u'': <''ちゅ''>, ''t-y-e'': <''ちぇ''>, ''t-y-o'': <''ちょ''>, ''c-y-a'': <''ちゃ''>, ''c-y-i'': <''ちぃ''>, ''c-y-u'': <''ちゅ''>, ''c-y-e'': <''ちぇ''>, ''c-y-o'': <''ちょ''>, ''c-h-a'': <''ちゃ''>, ''c-h-i'': <''ち''>, ''c-h-u'': <''ちゅ''>, ''c-h-e'': <''ちぇ''>, ''c-h-o'': <''ちょ''>, ''d-y-a'': <''ぢゃ''>, ''d-y-i'': <''ぢぃ''>, ''d-y-u'': <''ぢゅ''>, ''d-y-e'': <''ぢぇ''>, ''d-y-o'': <''ぢょ''>, ''t-s-a'': <''つぁ''>, ''t-s-i'': <''つぃ''>, ''t-s-e'': <''つぇ''>, ''t-s-o'': <''つぉ''>, ''t-s-y-a'': <''つゃ''>, ''t-s-y-u'': <''つゅ''>, ''t-s-y-e'': <''つぃぇ''>, ''t-s-y-o'': <''つょ''>, ''d-z-a'': <''づぁ''>, ''d-z-i'': <''づぃ''>, ''d-z-u'': <''づ''>, ''d-z-e'': <''づぇ''>, ''d-z-o'': <''づぉ''>, ''d-z-y-a'': <''づゃ''>, ''d-z-y-u'': <''づゅ''>, ''d-z-y-e'': <''づぃぇ''>, ''d-z-y-o'': <''づょ''>, ''t-h-a'': <''てゃ''>, ''t-h-i'': <''てぃ''>, ''t-h-u'': <''てゅ''>, ''t-h-e'': <''てぇ''>, ''t-h-o'': <''てょ''>, ''t-w-u'': <''とぅ''>, ''d-h-a'': <''でゃ''>, ''d-h-i'': <''でぃ''>, ''d-h-u'': <''でゅ''>, ''d-h-e'': <''でぇ''>, ''d-h-o'': <''でょ''>, ''d-w-u'': <''どぅ''>, ''n-a'': <''な''>, ''n-i'': <''に''>, ''n-u'': <''ぬ''>, ''n-e'': <''ね''>, ''n-o'': <''の''>, ''n-y-a'': <''にゃ''>, ''n-y-i'': <''にぃ''>, ''n-y-u'': <''にゅ''>, ''n-y-e'': <''にぇ''>, ''n-y-o'': <''にょ''>, ''h-a'': <''は''>, ''h-i'': <''ひ''>, ''h-u'': <''ふ''>, ''h-e'': <''へ''>, ''h-o'': <''ほ''>, ''b-a'': <''ば''>, ''b-i'': <''び''>, ''b-u'': <''ぶ''>, ''b-e'': <''べ''>, ''b-o'': <''ぼ''>, ''p-a'': <''ぱ''>, ''p-i'': <''ぴ''>, ''p-u'': <''ぷ''>, ''p-e'': <''ぺ''>, ''p-o'': <''ぽ''>, ''h-y-a'': <''ひゃ''>, ''h-y-i'': <''ひぃ''>, ''h-y-u'': <''ひゅ''>, ''h-y-e'': <''ひぇ''>, ''h-y-o'': <''ひょ''>, ''b-y-a'': <''びゃ''>, ''b-y-i'': <''びぃ''>, ''b-y-u'': <''びゅ''>, ''b-y-e'': <''びぇ''>, ''b-y-o'': <''びょ''>, ''p-y-a'': <''ぴゃ''>, ''p-y-i'': <''ぴぃ''>, ''p-y-u'': <''ぴゅ''>, ''p-y-e'': <''ぴぇ''>, ''p-y-o'': <''ぴょ''>, ''f-a'': <''ふぁ''>, ''f-i'': <''ふぃ''>, ''f-u'': <''ふ''>, ''f-e'': <''ふぇ''>, ''f-o'': <''ふぉ''>, ''f-y-a'': <''ふゃ''>, ''f-y-i'': <''ふぃ''>, ''f-y-u'': <''ふゅ''>, ''f-y-e'': <''ふぇ''>, ''f-y-o'': <''ふょ''>, ''b-w-a'': <''ぶぁ''>, ''b-w-e'': <''ぶぇ''>, ''b-w-o'': <''ぶぉ''>, ''p-w-a'': <''ぷぁ''>, ''p-w-e'': <''ぷぇ''>, ''p-w-o'': <''ぷぉ''>, ''m-a'': <''ま''>, ''m-i'': <''み''>, ''m-u'': <''む''>, ''m-e'': <''め''>, ''m-o'': <''も''>, ''m-y-a'': <''みゃ''>, ''m-y-i'': <''みぃ''>, ''m-y-u'': <''みゅ''>, ''m-y-e'': <''みぇ''>, ''m-y-o'': <''みょ''>, ''y-a'': <''や''>, ''y-i'': <''い''>, ''y-u'': <''ゆ''>, ''y-e'': <''いぇ''>, ''y-o'': <''よ''>, ''l-y-a'': <''ゃ''>, ''l-y-i'': <''ぃ''>, ''l-y-u'': <''ゅ''>, ''l-y-e'': <''ぇ''>, ''l-y-o'': <''ょ''>, ''x-y-a'': <''ゃ''>, ''x-y-i'': <''ぃ''>, ''x-y-u'': <''ゅ''>, ''x-y-e'': <''ぇ''>, ''x-y-o'': <''ょ''>, ''r-a'': <''ら''>, ''r-i'': <''り''>, ''r-u'': <''る''>, ''r-e'': <''れ''>, ''r-o'': <''ろ''>, ''r-y-a'': <''りゃ''>, ''r-y-i'': <''りぃ''>, ''r-y-u'': <''りゅ''>, ''r-y-e'': <''りぇ''>, ''r-y-o'': <''りょ''>, ''w-a'': <''わ''>, ''w-i'': <''うぃ''>, ''w-u'': <''う''>, ''w-e'': <''うぇ''>, ''w-o'': <''を''>, ''l-w-a'': <''ゎ''>, ''x-w-a'': <''ゎ''>, ''n-apostrophe'': <''ん''>, ''n-n'': <''ん''>, ''w-y-i'': <''ゐ''>, ''w-y-e'': <''ゑ''>}>}'),
    @('a{sv}', '{''jp'': <{''1'': <''ぬ''>, ''2'': <''ふ''>, ''3'': <''あ''>, ''4'': <''う''>, ''5'': <''え''>, ''6'': <''お''>, ''7'': <''や''>, ''8'': <''ゆ''>, ''9'': <''よ''>, ''0'': <''わ''>, ''minus'': <''ほ''>, ''asciicircum'': <''へ''>, ''q'': <''た''>, ''w'': <''て''>, ''e'': <''い''>, ''r'': <''す''>, ''t'': <''か''>, ''y'': <''ん''>, ''u'': <''な''>, ''i'': <''に''>, ''o'': <''ら''>, ''p'': <''せ''>, ''at'': <''゛''>, ''bracketleft'': <''゜''>, ''a'': <''ち''>, ''s'': <''と''>, ''d'': <''し''>, ''f'': <''は''>, ''g'': <''き''>, ''h'': <''く''>, ''j'': <''ま''>, ''k'': <''の''>, ''l'': <''り''>, ''semicolon'': <''れ''>, ''colon'': <''け''>, ''bracketright'': <''む''>, ''z'': <''つ''>, ''x'': <''さ''>, ''c'': <''そ''>, ''v'': <''ひ''>, ''b'': <''こ''>, ''n'': <''み''>, ''m'': <''も''>, ''comma'': <''ね''>, ''period'': <''る''>, ''slash'': <''め''>, ''backslash'': <''ろ''>, ''exclam'': <''ぬ''>, ''quotedbl'': <''ふ''>, ''numbersign'': <''ぁ''>, ''dollar'': <''ぅ''>, ''percent'': <''ぇ''>, ''ampersand'': <''ぉ''>, ''apostrophe'': <''ゃ''>, ''parenleft'': <''ゅ''>, ''parenright'': <''ょ''>, ''asciitilde'': <''を''>, ''equal'': <''ゑ''>, ''bar'': <''ー''>, ''largeq'': <''た''>, ''largew'': <''て''>, ''largee'': <''ぃ''>, ''larger'': <''す''>, ''larget'': <''ヵ''>, ''largey'': <''ん''>, ''largeu'': <''な''>, ''largei'': <''に''>, ''largeo'': <''ら''>, ''largep'': <''せ''>, ''grave'': <''゛''>, ''braceleft'': <''「''>, ''largea'': <''ち''>, ''larges'': <''と''>, ''larged'': <''し''>, ''largef'': <''ゎ''>, ''largeg'': <''き''>, ''largeh'': <''く''>, ''largej'': <''ま''>, ''largek'': <''の''>, ''largel'': <''り''>, ''plus'': <''れ''>, ''asterisk'': <''ヶ''>, ''braceright'': <''」''>, ''largez'': <''っ''>, ''largex'': <''さ''>, ''largec'': <''そ''>, ''largev'': <''ゐ''>, ''largeb'': <''こ''>, ''largen'': <''み''>, ''largem'': <''も''>, ''less'': <''、''>, ''greater'': <''。''>, ''question'': <''・''>, ''underscore'': <''ろ''>, ''yen'': <''ー''>}>, ''us'': <{''grave'': <''ろ''>, ''1'': <''ぬ''>, ''2'': <''ふ''>, ''3'': <''あ''>, ''4'': <''う''>, ''5'': <''え''>, ''6'': <''お''>, ''7'': <''や''>, ''8'': <''ゆ''>, ''9'': <''よ''>, ''0'': <''わ''>, ''minus'': <''ほ''>, ''equal'': <''へ''>, ''q'': <''た''>, ''w'': <''て''>, ''e'': <''い''>, ''r'': <''す''>, ''t'': <''か''>, ''y'': <''ん''>, ''u'': <''な''>, ''i'': <''に''>, ''o'': <''ら''>, ''p'': <''せ''>, ''bracketleft'': <''゛''>, ''bracketright'': <''゜''>, ''backslash'': <''む''>, ''a'': <''ち''>, ''s'': <''と''>, ''d'': <''し''>, ''f'': <''は''>, ''g'': <''き''>, ''h'': <''く''>, ''j'': <''ま''>, ''k'': <''の''>, ''l'': <''り''>, ''semicolon'': <''れ''>, ''apostrophe'': <''け''>, ''z'': <''つ''>, ''x'': <''さ''>, ''c'': <''そ''>, ''v'': <''ひ''>, ''b'': <''こ''>, ''n'': <''み''>, ''m'': <''も''>, ''comma'': <''ね''>, ''period'': <''る''>, ''slash'': <''め''>, ''asciitilde'': <''ろ''>, ''exclam'': <''ぬ''>, ''at'': <''ふ''>, ''numbersign'': <''ぁ''>, ''dollar'': <''ぅ''>, ''percent'': <''ぇ''>, ''asciicircum'': <''ぉ''>, ''ampersand'': <''ゃ''>, ''asterisk'': <''ゅ''>, ''parenleft'': <''ょ''>, ''parenright'': <''を''>, ''underscore'': <''ー''>, ''plus'': <''ゑ''>, ''largeq'': <''た''>, ''largew'': <''て''>, ''largee'': <''ぃ''>, ''larger'': <''す''>, ''larget'': <''ヵ''>, ''largey'': <''ん''>, ''largeu'': <''な''>, ''largei'': <''に''>, ''largeo'': <''ら''>, ''largep'': <''せ''>, ''braceleft'': <''「''>, ''braceright'': <''」''>, ''bar'': <''む''>, ''largea'': <''ち''>, ''larges'': <''と''>, ''larged'': <''し''>, ''largef'': <''ゎ''>, ''largeg'': <''き''>, ''largeh'': <''く''>, ''largej'': <''ま''>, ''largek'': <''の''>, ''largel'': <''り''>, ''colon'': <''れ''>, ''quotedbl'': <''ヶ''>, ''largez'': <''っ''>, ''largex'': <''さ''>, ''largec'': <''そ''>, ''largev'': <''ゐ''>, ''largeb'': <''こ''>, ''largen'': <''み''>, ''largem'': <''も''>, ''less'': <''、''>, ''greater'': <''。''>, ''question'': <''・''>}>}'),
    @('a(sss)', '@a(sss) []'),
    @('aa{sv}', '[{''name'': <''DuckDuckGo''>, ''url'': <''https://duckduckgo.com/?q=%s&t=epiphany&kd=-1''>, ''bang'': <''!ddg''>}, {''name'': <''Google''>, ''url'': <''https://www.google.com/search?q=%s''>, ''bang'': <''!g''>}, {''name'': <''Bing''>, ''url'': <''https://www.bing.com/search?q=%s''>, ''bang'': <''!b''>}]'),
    @('aa{sv}', '[{''org.fedoraproject.MediaWriter.desktop'': <{''position'': <0>}>, ''org.gnome.Contacts.desktop'': <{''position'': <1>}>, ''org.gnome.Weather.desktop'': <{''position'': <2>}>, ''org.gnome.clocks.desktop'': <{''position'': <3>}>, ''org.gnome.Maps.desktop'': <{''position'': <4>}>, ''libreoffice-calc.desktop'': <{''position'': <5>}>, ''libreoffice-impress.desktop'': <{''position'': <6>}>, ''org.gnome.Totem.desktop'': <{''position'': <7>}>, ''org.gnome.Calculator.desktop'': <{''position'': <8>}>, ''libreoffice-writer.desktop'': <{''position'': <9>}>, ''simple-scan.desktop'': <{''position'': <10>}>, ''org.gnome.Settings.desktop'': <{''position'': <11>}>, ''org.gnome.Boxes.desktop'': <{''position'': <12>}>, ''org.gnome.Terminal.desktop'': <{''position'': <13>}>, ''Utilities'': <{''position'': <14>}>, ''org.gnome.Rhythmbox3.desktop'': <{''position'': <15>}>, ''yelp.desktop'': <{''position'': <16>}>, ''org.gnome.TextEditor.desktop'': <{''position'': <17>}>, ''org.gnome.Cheese.desktop'': <{''position'': <18>}>, ''org.gnome.Tour.desktop'': <{''position'': <19>}>, ''alsamixergui.desktop'': <{''position'': <20>}>, ''conky.desktop'': <{''position'': <21>}>, ''org.coolercontrol.CoolerControl.desktop'': <{''position'': <22>}>}, {''emacs.desktop'': <{''position'': <0>}>, ''org.flameshot.Flameshot.desktop'': <{''position'': <1>}>, ''Battlefield 1.desktop'': <{''position'': <2>}>, ''bitcoin-qt.desktop'': <{''position'': <3>}>, ''links.desktop'': <{''position'': <4>}>, ''system-config-printer.desktop'': <{''position'': <5>}>, ''com.blackmagicdesign.rawplayer.desktop'': <{''position'': <6>}>, ''rofi.desktop'': <{''position'': <7>}>, ''rofi-theme-selector.desktop'': <{''position'': <8>}>, ''DEATHLOOP.desktop'': <{''position'': <9>}>, ''rxvt-unicode.desktop'': <{''position'': <10>}>, ''me.ahola.aphototoollibre.desktop'': <{''position'': <11>}>, ''code.desktop'': <{''position'': <12>}>, ''vlc.desktop'': <{''position'': <13>}>, ''io.gitlab.librewolf-community.desktop'': <{''position'': <14>}>, ''com.mattermost.Desktop.desktop'': <{''position'': <15>}>, ''mullvad-vpn.desktop'': <{''position'': <16>}>, ''com.blackmagicdesign.rawspeedtest.desktop'': <{''position'': <17>}>, ''com.blackmagicdesign.resolve-CaptureLogs.desktop'': <{''position'': <18>}>, ''com.blackmagicdesign.resolve-Panels.desktop'': <{''position'': <19>}>, ''com.blackmagicdesign.resolve.desktop'': <{''position'': <20>}>, ''drracket.desktop'': <{''position'': <21>}>, ''net.longturn.freeciv21.desktop'': <{''position'': <22>}>, ''aerc.desktop'': <{''position'': <23>}>}, {''net.longturn.freeciv21.modpack-qt.desktop'': <{''position'': <0>}>, ''net.longturn.freeciv21.ruledit.desktop'': <{''position'': <1>}>, ''net.longturn.freeciv21.server.desktop'': <{''position'': <2>}>, ''Into the Breach.desktop'': <{''position'': <3>}>, ''lvim.desktop'': <{''position'': <4>}>, ''nvim.desktop'': <{''position'': <5>}>, ''engineer.atlas.Nyxt.desktop'': <{''position'': <6>}>, ''Proton Experimental.desktop'': <{''position'': <7>}>, ''DOOM Eternal.desktop'': <{''position'': <8>}>, ''slideshow.desktop'': <{''position'': <9>}>, ''steam.desktop'': <{''position'': <10>}>, ''Steam Linux Runtime 3.0 (sniper).desktop'': <{''position'': <11>}>, ''System Shock.desktop'': <{''position'': <12>}>, ''balena-etcher.desktop'': <{''position'': <13>}>, ''com.blackmagicdesign.resolve-Installer.desktop'': <{''position'': <14>}>, ''emoji-picker.desktop'': <{''position'': <15>}>, ''org.gnome.Snapshot.desktop'': <{''position'': <16>}>, ''ca.desrt.dconf-editor.desktop'': <{''position'': <17>}>, ''Dead Space (2008).desktop'': <{''position'': <18>}>, ''Desperados III.desktop'': <{''position'': <19>}>, ''discord.desktop'': <{''position'': <20>}>, ''org.gnome.Extensions.desktop'': <{''position'': <21>}>, ''org.gimp.GIMP.desktop'': <{''position'': <22>}>, ''gparted.desktop'': <{''position'': <23>}>}, {''io.github.arunsivaramanneo.GPUViewer.desktop'': <{''position'': <0>}>, ''foot.desktop'': <{''position'': <1>}>, ''footclient.desktop'': <{''position'': <2>}>, ''foot-server.desktop'': <{''position'': <3>}>, ''GameConqueror.desktop'': <{''position'': <4>}>, ''htop.desktop'': <{''position'': <5>}>, ''yad-icon-browser.desktop'': <{''position'': <6>}>, ''page.codeberg.JakobDev.jdSimpleAutostart.desktop'': <{''position'': <7>}>, ''Inkulinati.desktop'': <{''position'': <8>}>, ''keepass.desktop'': <{''position'': <9>}>, ''org.sugarlabs.Measure.desktop'': <{''position'': <10>}>, ''Metro Last Light Redux.desktop'': <{''position'': <11>}>, ''md.obsidian.Obsidian.desktop'': <{''position'': <12>}>, ''METAL GEAR SOLID V THE PHANTOM PAIN.desktop'': <{''position'': <13>}>, ''Proton EasyAntiCheat Runtime.desktop'': <{''position'': <14>}>, ''org.remmina.Remmina.desktop'': <{''position'': <15>}>, ''org.gnome.World.Secrets.desktop'': <{''position'': <16>}>, ''Shadow Tactics Blades of the Shogun.desktop'': <{''position'': <17>}>, ''org.signal.Signal.desktop'': <{''position'': <18>}>, ''syncthing-start.desktop'': <{''position'': <19>}>, ''syncthing-ui.desktop'': <{''position'': <20>}>, ''org.gnome.SystemMonitor.desktop'': <{''position'': <21>}>, ''org.telegram.desktop.desktop'': <{''position'': <22>}>, ''org.telegram.desktop._05d2f36494b7927249e4e418951a484f.desktop'': <{''position'': <23>}>}, {''org.mozilla.thunderbird.desktop'': <{''position'': <0>}>, ''Toby The Secret Mine.desktop'': <{''position'': <1>}>, ''transmission-gtk.desktop'': <{''position'': <2>}>, ''io.github.TransmissionRemoteGtk.desktop'': <{''position'': <3>}>, ''virt-manager.desktop'': <{''position'': <4>}>, ''Phoenix Point.desktop'': <{''position'': <5>}>, ''org.wireshark.Wireshark.desktop'': <{''position'': <6>}>, ''us.zoom.Zoom.desktop'': <{''position'': <7>}>, ''Trepang2.desktop'': <{''position'': <8>}>, ''INSIDE.desktop'': <{''position'': <9>}>, ''Control Ultimate Edition.desktop'': <{''position'': <10>}>, ''com.mattjakeman.ExtensionManager.desktop'': <{''position'': <11>}>, ''Proton 9.0.desktop'': <{''position'': <12>}>, "Sid Meier''s Civilization VI.desktop": <{''position'': <13>}>, ''com.spotify.Client.desktop'': <{''position'': <14>}>, ''steamtinkerlaunch.desktop'': <{''position'': <15>}>, ''Superliminal.desktop'': <{''position'': <16>}>, ''io.github.ungoogled_software.ungoogled_chromium.desktop'': <{''position'': <17>}>, ''Wasteland 2.desktop'': <{''position'': <18>}>, ''XCOM 2.desktop'': <{''position'': <19>}>}]'),
    @('aa{sv}', '@aa{sv} []'),
    @('(bbsmv)', '(true, true, '''', @mv nothing)'),
    @('(bdddd)', '(true, 0.0, 0.0, 0.0, 1.0)'),
    @('(bdddd)', '(true, 0.20784313976764679, 0.51764708757400513, 0.89411765336990356, 1.0)'),
    @('a(dddd)', '[(0.75, 0.25, 0.25, 1.0)]'),
    @('a(dddd)', '[(0.97647058823529409, 0.97647058823529409, 0.98039215686274506, 1.0)]'),
    @('(ssm(dd))', '('''', ''EGLL'', @m(dd) nothing)'),
    @('a((auss)u)', '@a((auss)u) []'),
    @('a((aussasasu)u)', '@a((aussasasu)u) []')
    # ,
    # @('org.gnome.clocks.panelid', '''world'''),
    # @('org.gnome.boxes.view-type', '''list-view'''),
    # @('org.gnome.Logs.GlSortOrder', '''descending-time'''),
    # @('org.gnome.Evince.SizingMode', '''free'''),
    # @('org.gnome.nautilus.SortOrder', '''name'''),
    # @('org.gnome.nautilus.FolderView', '''list-view'''),
    # @('org.gnome.SimpleScan.PageSide', '''both'''),
    # @('ca.desrt.dconf-editor.DemoEnum', '''White'''),
    # @('org.gnome.calculator.AngleUnit', '''degrees'''),
    # @('org.gnome.nautilus.ClickPolicy', '''double'''),
    # @('org.gnome.Snapshot.CaptureMode', '''picture'''),
    # @('org.gnome.Snapshot.VideoFormat', '''vp8webm'''),
    # @('org.gnome.Terminal.TabPosition', '''top'''),
    # @('ca.desrt.dconf-editor.Behaviour', '''always-confirm-implicit'''),
    # @('ca.desrt.dconf-editor.DemoFlags', '[''Blue'', ''White'', ''Red'']'),
    # @('org.gnome.calculator.ButtonMode', '''basic'''),
    # @('org.gnome.Terminal.ThemeVariant', '''dark'''),
    # @('org.gnome.TextEditor.DrawSpaces', '@as []'),
    # @('org.gnome.nautilus.GridZoomLevel', '''medium'''),
    # @('org.gnome.nautilus.ListZoomLevel', '''medium'''),
    # @('org.gnome.nautilus.SpeedTradeoff', '''local-only'''),
    # @('org.gnome.Snapshot.PictureFormat', '''jpeg'''),
    # @('org.gnome.Terminal.TabsbarPolicy', '''automatic'''),
    # @('org.gnome.calculator.NumberFormat', '''automatic'''),
    # @('org.gnome.calendar.GcalWindowView', '''month'''),
    # @('org.gnome.maps.TransportationType', '''pedestrian'''),
    # @('org.gnome.nautilus.DateTimeFormat', '''simple'''),
    # @('org.gnome.Terminal.NewTabPosition', '''last'''),
    # @('org.gnome.Terminal.NewTerminalMode', '''window'''),
    # @('org.gnome.totem.BvwAudioOutputType', '''stereo'''),
    # @('ca.desrt.dconf-editor.DemoWeirdEnum', '''only-choice'''),
    # @('org.gnome.desktop.GDesktopFocusMode', '''click'''),
    # @('org.gnome.desktop.GDesktopProxyMode', '''none'''),
    # @('org.gnome.nautilus.CompressionFormat', '''zip'''),
    # @('org.gnome.rhythmbox.podcast-interval', '''hourly'''),
    # @('org.gnome.desktop.GDesktopClockFormat', '''24h'''),
    # @('org.gnome.desktop.GDesktopColorScheme', '''prefer-dark'''),
    # @('org.gnome.desktop.GDesktopFontHinting', '''slight'''),
    # @('org.gnome.GWeather4.GWeatherSpeedUnit', '''default'''),
    # @('org.gnome.settings-daemon.GsdBellMode', '''on'''),
    # @('org.gnome.desktop.GDesktopToolbarStyle', '''both-horiz'''),
    # @('org.gtk.Settings.FileChooser.SortOrder', '''descending'''),
    # @('org.gnome.desktop.GDesktopFontRgbaOrder', '''rgb'''),
    # @('org.gnome.desktop.GDesktopUsbProtection', '''lockscreen'''),
    # @('org.gnome.nautilus.SearchFilterTimeType', '''last_modified'''),
    # @('org.gtk.Settings.FileChooser.DateFormat', '''regular'''),
    # @('org.gtk.Settings.FileChooser.SortColumn', '''modified'''),
    # @('org.gtk.Settings.FileChooser.TypeFormat', '''category'''),
    # @('org.gnome.desktop.GDesktopMouseDwellMode', '''window'''),
    # @('org.gnome.desktop.GDesktopTitlebarAction', '''menu'''),
    # @('org.gnome.desktop.GDesktopTitlebarAction', '''none'''),
    # @('org.gnome.desktop.GDesktopTitlebarAction', '''toggle-maximize'''),
    # @('org.gnome.desktop.GDesktopVisualBellType', '''fullscreen-flash'''),
    # @('org.gnome.GWeather4.GWeatherDistanceUnit', '''default'''),
    # @('org.gnome.GWeather4.GWeatherPressureUnit', '''default'''),
    # @('org.gnome.mutter.MetaExperimentalFeature', '@as []'),
    # @('org.gtk.Settings.FileChooser.ClockFormat', '''24h'''),
    # @('org.gtk.Settings.FileChooser.StartupMode', '''recent'''),
    # @('org.gnome.desktop.GDesktopBackgroundStyle', '''zoom'''),
    # @('org.gnome.desktop.GDesktopFocusNewWindows', '''smart'''),
    # @('org.gnome.desktop.GDesktopToolbarIconSize', '''large'''),
    # @('org.gtk.Settings.FileChooser.LocationMode', '''path-bar'''),
    # @('org.gnome.desktop.GDesktopDeviceSendEvents', '''enabled'''),
    # @('org.gtk.gtk4.Settings.FileChooser.ViewType', '''list'''),
    # @('org.gnome.desktop.GDesktopBackgroundShading', '''solid'''),
    # @('org.gnome.Epiphany.EphyPrefsReaderFontStyle', '''sans'''),
    # @('org.gnome.GWeather4.GWeatherTemperatureUnit', '''default'''),
    # @('org.gnome.rhythmbox.plugins.replaygain.mode', '''radio'''),
    # @('org.gnome.shell.window-switcher.AppIconMode', '''both'''),
    # @('org.gtk.gtk4.Settings.FileChooser.SortOrder', '''ascending'''),
    # @('org.gnome.desktop.GDesktopTouchpadHandedness', '''mouse'''),
    # @('org.gnome.settings-daemon.GsdPowerActionType', '''suspend'''),
    # @('org.gtk.gtk4.Settings.FileChooser.DateFormat', '''regular'''),
    # @('org.gtk.gtk4.Settings.FileChooser.SortColumn', '''name'''),
    # @('org.gtk.gtk4.Settings.FileChooser.TypeFormat', '''category'''),
    # @('org.gnome.desktop.GDesktopMouseDwellDirection', '''down'''),
    # @('org.gnome.desktop.GDesktopMouseDwellDirection', '''left'''),
    # @('org.gnome.desktop.GDesktopMouseDwellDirection', '''right'''),
    # @('org.gnome.desktop.GDesktopMouseDwellDirection', '''up'''),
    # @('org.gnome.desktop.GDesktopPointerAccelProfile', '''default'''),
    # @('org.gnome.desktop.GDesktopTouchpadClickMethod', '''fingers'''),
    # @('org.gnome.Epiphany.EphyPrefsReaderColorScheme', '''light'''),
    # @('org.gnome.mutter.MetaXwaylandDisableExtension', '@as []'),
    # @('org.gtk.gtk4.Settings.FileChooser.ClockFormat', '''24h'''),
    # @('org.gtk.gtk4.Settings.FileChooser.StartupMode', '''recent'''),
    # @('org.gnome.desktop.GDesktopFontAntialiasingMode', '''grayscale'''),
    # @('org.gnome.desktop.GDesktopTouchpadTapButtonMap', '''default'''),
    # @('org.gnome.rhythmbox.sources.browser-view-types', '''artists-albums'''),
    # @('org.gtk.gtk4.Settings.FileChooser.LocationMode', '''path-bar'''),
    # @('org.gnome.desktop.GDesktopLocationAccuracyLevel', '''exact'''),
    # @('org.gnome.Epiphany.EphyPrefsRestoreSessionPolicy', '''always'''),
    # @('org.gnome.desktop.GDesktopMagnifierScreenPosition', '''full-screen'''),
    # @('org.gnome.desktop.remote-desktop.GrdVncAuthMethod', '''prompt'''),
    # @('org.gnome.desktop.remote-desktop.GrdVncEncryption', '[''tls-anon'']'),
    # @('org.gnome.evolution-data-server.calendar.Duration', '''minutes'''),
    # @('org.gnome.settings-daemon.GsdPowerButtonActionType', '''suspend'''),
    # @('org.fedorahosted.background-logo-extension.Position', '''bottom-right'''),
    # @('org.gnome.desktop.GDesktopPointingStickScrollMethod', '''default'''),
    # @('org.gnome.settings-daemon.GsdSmartcardRemovalAction', '''none'''),
    # @('org.gnome.shell.extensions.window-list.GroupingMode', '''never'''),
    # @('org.gnome.system.gvfs.GVfsBackendNetworkDisplayMode', '''disabled'''),
    # @('org.gnome.system.gvfs.GVfsBackendNetworkDisplayMode', '''merged'''),
    # @('org.gnome.desktop.GDesktopMagnifierCaretTrackingMode', '''centered'''),
    # @('org.gnome.desktop.GDesktopMagnifierFocusTrackingMode', '''proportional'''),
    # @('org.gnome.desktop.GDesktopMagnifierMouseTrackingMode', '''proportional'''),
    # @('org.gnome.Epiphany.EphyPrefsUITabsBarVisibilityPolicy', '''more-than-one'''),
    # @('org.gnome.desktop.remote-desktop.GrdRdpScreenShareMode', '''mirror-primary'''),
    # @('org.gnome.desktop.remote-desktop.GrdVncScreenShareMode', '''mirror-primary'''),
    # @('ca.desrt.dconf-editor.RelocatableSchemasEnabledMappings', '[''User'', ''Built-in'', ''Internal'', ''Startup'']')
)
